#!/usr/bin/env bash
# compile autogen_tl, make neovim run it

set -euo pipefail

NVIM_BIN="${NVIM_BIN:-"nvim"}"

tl check autogen_tl -q
tl gen autogen_tl --skip-compat53 -q -o "autogen.lua"

"$NVIM_BIN" --noplugin -u NORC --headless -n "+luafile autogen.lua" "+q"

rm "autogen.lua"
