#!/usr/bin/env bash
# compile autogen_tl, make neovim run it

set -euo pipefail

cleanup() {
  rm -f "empty.d.tl" "autogen.lua"
}

trap "cleanup" EXIT

NVIM_BIN="${NVIM_BIN:-"nvim"}"

touch "empty.d.tl"

tl check --global-env-def "empty" -q "autogen_tl"
tl gen --global-env-def "empty" --skip-compat53 -q -o "autogen.lua" "autogen_tl"

"$NVIM_BIN" --noplugin -u NORC --headless -n "+luafile autogen.lua" "+q"
